version: '3.4'

services:
  
  temp-api:
    image: temp-api
    build:
      context: .
      dockerfile: TempApi/Dockerfile
    networks:
      - sample-net
      
  humid-api:
    image: humid-api
    build:
      context: .
      dockerfile: HumidApi/Dockerfile
    networks:
      - sample-net

  aggregator-api:
    image: aggregator-api
    build:
      context: .
      dockerfile: AggregatorApi/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - temp-api
      - humid-api
    networks:
      - sample-net
  
networks:
  sample-net: