version: '3.4'

services:
  
  temp-api:
    image: temp-api
    build:
      context: .
      dockerfile: TempApi/Dockerfile
    networks:
      - sample-net
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      
  humid-api:
    image: humid-api
    build:
      context: .
      dockerfile: HumidApi/Dockerfile
    networks:
      - sample-net
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  aggregator-api:
    image: aggregator-api
    build:
      context: .
      dockerfile: AggregatorApi/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - temp-api
      - humid-api
    networks:
      - sample-net
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  
networks:
  sample-net: